In [9]:
import _init_paths
from datasets.factory import get_imdb
import cv2
import visdom
import numpy as np
from PIL import Image
# vis = visdom.Visdom(server='http://localhost',port='8097')
imdb = get_imdb('voc_2007_trainval')
imdb.classes
idx =2018
img_path = imdb.image_path_at(idx)
img = cv2.imread(img_path)
img_pil = Image.open(img_path)
print list(img_pil.getdata())
roidb = imdb.roidb
print len(roidb)
boxes = roidb[idx]['boxes']
print boxes.shape
for box in boxes[:10,:]:
    cv2.rectangle(img,(box[0],box[1]),(box[2],box[3]),(0,0,255),3)
data = np.asarray(img)
data = np.transpose(data, [2,0,1])
# data = data +img
# vis.image(data)

# from matplotlib import pyplot as plt
# plt.imshow(img)
# plt.show()    
print imdb.num_images


[(127, 133, 133), (124, 130, 130), (120, 126, 126), (121, 125, 126), (119, 123, 124), (114, 118, 119), (109, 113, 116), (101, 104, 109), (96, 99, 106), (97, 100, 109), (97, 100, 109), (96, 99, 108), (97, 100, 109), (99, 103, 112), (110, 115, 121), (125, 130, 136), (137, 155, 165), (171, 189, 199), (196, 213, 223), (219, 233, 246), (225, 237, 249), (240, 250, 255), (240, 248, 255), (247, 254, 255), (246, 251, 255), (252, 255, 255), (252, 253, 255), (254, 254, 254), (252, 252, 250), (254, 254, 252), (254, 253, 251), (253, 252, 250), (254, 253, 255), (254, 252, 255), (253, 251, 254), (253, 251, 252), (255, 252, 253), (255, 251, 250), (255, 251, 250), (255, 252, 249), (255, 252, 249), (255, 252, 251), (254, 253, 251), (255, 253, 254), (254, 254, 254), (253, 254, 255), (253, 254, 255), (251, 255, 255), (250, 254, 253), (251, 255, 254), (252, 255, 255), (254, 255, 255), (254, 255, 255), (254, 255, 255), (253, 255, 254), (253, 255, 254), (254, 255, 255), (254, 255, 255), (254, 255, 255), (254

voc_2007_trainval ss roidb loaded from /home/studio/Documents/aman/crystal_test/hw2-release/code/data/cache/voc_2007_trainval_selective_search_roidb.pkl
5011
(2853, 4)
5011


In [6]:
gt_roidb = imdb.gt_roidb()
gt_boxes = gt_roidb[2018]['boxes']
print gt_boxes.shape
for bbox in gt_boxes:
    cv2.rectangle(img, (box[0],box[1]),(box[2],box[3]), (0, 204, 0), 2)
# plt.imshow(img)
# plt.show()
data = np.asarray(img)
data = np.transpose(data, [2,0,1])
# vis.image(data)
gt_roidb[30]['gt_classes']

voc_2007_trainval gt roidb loaded from /home/studio/Documents/aman/crystal_test/hw2-release/code/data/cache/voc_2007_trainval_gt_roidb.pkl
(1, 4)


array([19], dtype=int32)

In [7]:
gt_roidb[30]['gt_classes']

array([12,  9], dtype=int32)

In [5]:
print np.asarray(img_pil.getdata())

[[127 133 133]
 [124 130 130]
 [120 126 126]
 ..., 
 [131 126 123]
 [133 128 125]
 [128 123 120]]


In [7]:
imdb.classes

('aeroplane',
 'bicycle',
 'bird',
 'boat',
 'bottle',
 'bus',
 'car',
 'cat',
 'chair',
 'cow',
 'diningtable',
 'dog',
 'horse',
 'motorbike',
 'person',
 'pottedplant',
 'sheep',
 'sofa',
 'train',
 'tvmonitor')

In [10]:
np.asarray(list(img_pil.getdata())).max()


255